openapi: 3.0.3
info:
  title: Randomcraft
  description: Randomcraft
  version: 1.0.0
servers:
  - url: 'http://localhost:9090'
paths:
  /ability:
    get:
      summary: Returns a list of abilities
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
