spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/randomstarcraft
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: randomcraft.application.util.TableNamingStrategy

# logging
logging:
  level:
    web: debug
    org:
      springframework:
        web: debug